// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABL0AeQiyrDSdvezapIC7lTD35a8yVbik',
    appId: '1:86192589121:web:c8b8766ec8813acf7539c0',
    messagingSenderId: '86192589121',
    projectId: 'fevly-5adae',
    authDomain: 'fevly-5adae.firebaseapp.com',
    storageBucket: 'fevly-5adae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYtmTf8_jScCrocpjNUjjh368_MniVMoM',
    appId: '1:86192589121:android:780fcdb5e7333d797539c0',
    messagingSenderId: '86192589121',
    projectId: 'fevly-5adae',
    storageBucket: 'fevly-5adae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-0owhWsNorIorQzP8GkR85qrMxiP598',
    appId: '1:86192589121:ios:1085b594bad234257539c0',
    messagingSenderId: '86192589121',
    projectId: 'fevly-5adae',
    storageBucket: 'fevly-5adae.appspot.com',
    iosClientId: '86192589121-4o84tg1c8itktn5slt5fmnuaj6sh68l2.apps.googleusercontent.com',
    iosBundleId: 'com.fevly.fevly',
  );
}
