// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDshqljbFmgCcBx6PMnnj8vbAkHTM_SDao',
    appId: '1:86192589121:web:ef6748b1c33331767539c0',
    messagingSenderId: '86192589121',
    projectId: 'fevly-5adae',
    authDomain: 'fevly-5adae.firebaseapp.com',
    storageBucket: 'fevly-5adae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNCsFtBFTdX76nOVg8nGczEAZIFkij5Kc',
    appId: '1:86192589121:android:dfe2cd58b9dba90d7539c0',
    messagingSenderId: '86192589121',
    projectId: 'fevly-5adae',
    storageBucket: 'fevly-5adae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlE2nDhXPXvdA7MZxoIm7geCrINPGJztU',
    appId: '1:86192589121:ios:bae7141b85ee02b17539c0',
    messagingSenderId: '86192589121',
    projectId: 'fevly-5adae',
    storageBucket: 'fevly-5adae.appspot.com',
    iosClientId: '86192589121-n24ddatlpscbgqi19shnh3giift49lu0.apps.googleusercontent.com',
    iosBundleId: 'fevly',
  );
}
